// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelatorioPacientes.Models;

#nullable disable

namespace RelatorioPacientes.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230216003121_Inicial-criacao")]
    partial class Inicialcriacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelatorioPacientes.Models.Paciente", b =>
                {
                    b.Property<int>("MRN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MRN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MRN"));

                    b.Property<int>("CPF")
                        .HasColumnType("int")
                        .HasColumnName("CPF");

                    b.Property<int>("DateOfBirth")
                        .HasColumnType("int")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("MRN");

                    b.ToTable("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
